// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpMWEWqwLRX58Wx7OBNFngZiMyev2gYQ0',
    appId: '1:568600623306:web:4af39937b6ae12e9f55c33',
    messagingSenderId: '568600623306',
    projectId: 'book-now-2e829',
    authDomain: 'book-now-2e829.firebaseapp.com',
    storageBucket: 'book-now-2e829.appspot.com',
    measurementId: 'G-BH55CX1VF8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAX7J3v6Zm2TQVsgIP121DatWKaqWwHdbI',
    appId: '1:568600623306:android:0655548cc483787df55c33',
    messagingSenderId: '568600623306',
    projectId: 'book-now-2e829',
    storageBucket: 'book-now-2e829.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwcPAziub-quB_-Rpjj4ruicWhRuCsKhg',
    appId: '1:568600623306:ios:ee56e4939ec0cd7ff55c33',
    messagingSenderId: '568600623306',
    projectId: 'book-now-2e829',
    storageBucket: 'book-now-2e829.appspot.com',
    iosClientId: '568600623306-l23fludo86vj8hdeajgb46k7j7sn7hg2.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookNow',
  );
}
